- name: Create Loadbalancer
  hosts: loadbalancers
  connection: local
  gather_facts: no
  vars:
    lbName: "{{env_id}}-lb-{{inventory_hostname}}-pip"
    rgName: "{{env_id}}-rg-{{resource_group}}"
  tasks:
  - name: Create public IP address for LB
    azure_rm_publicipaddress:
      resource_group: "{{rgName}}"
      allocation_method: Dynamic
      name: "{{lbName}}-pip"
  - name: Create a load balancer
    azure_rm_loadbalancer:
     name: "{{lbName}}"
     location: "{{location}}"
     resource_group: "{{rgName}}"
     public_ip_address_name: "{{lbName}}-pip"
     probe_protocol: "{{probe_protocol}}"
     probe_port: "{{probe_port}}"
     probe_interval: "{{probe_interval}}"
     probe_fail_count: "{{probe_fail_count}}"
     protocol: "{{protocol}}"
     load_distribution: Default
     frontend_port: "{{frontend_port}}"
     backend_port: "{{backend_port}}"
     idle_timeout: 30
     natpool_frontend_port_start: "{{natpool_frontend_port_start}}"
     natpool_frontend_port_end: "{{natpool_frontend_port_end}}"
     natpool_backend_port: 22
     natpool_protocol: "{{natpool_protocol}}"