- name: Create Network
  hosts: vms
  connection: local
  vars:
    rgName: "{{env_id}}-rg-{{resource_group}}"
    vnet_name: "{{env_id}}-vnet"
  tasks:
    - name: Create public IP address
    azure_rm_publicipaddress:
      resource_group: "{{rgName}}"
      allocation_method: Dynamic
      name: "{{inventory_hostname}}-pip"
    - name: Create virtual network inteface card - FE
    azure_rm_networkinterface:
      resource_group: "{{rgName}}"
      name: "{{inventory_hostname}}-nic-fe"
      virtual_network: "{{env_id}}-vnet"
      subnet: "{{env_id}}-subnet-fe"
      security_group: "{{env_id}}-nsg-fe"
      ip_configurations:
        - name: ipconfig1
          private_ip_allocation_method: Static
          private_ip_address: "{{ansible_ssh_host}}"
          public_ip_address_name: "{{inventory_hostname}}-pip"
          primary: true
  - name: Create virtual network inteface card - BE
    azure_rm_networkinterface:
      resource_group: "{{rgName}}"
      name: "{{inventory_hostname}}-nic-be"
      virtual_network: "{{env_id}}-vnet"
      subnet: "{{env_id}}-subnet-be"
      security_group: "{{env_id}}-nsg-be"
      ip_configurations:
        - name: ipconfig1
          private_ip_allocation_method: Static
          private_ip_address: "{{secondary_ip}}"
