- name: Create Azure VM - {{ vm_name }}
  hosts: vms
  connection: local
  tasks:
  - name: Create virtual network
    azure_rm_virtualnetwork:
      resource_group: the1bit-rg-custom
      name: the1bit-vnet
      address_prefixes: "79.0.0.0/23"
  - name: Add FE subnet
    azure_rm_subnet:
      resource_group: the1bit-rg-custom
      name: the1bit-subnet-fe
      address_prefix: "79.0.0.0/24"
      virtual_network: the1bit-vnet
  - name: Add BE subnet
    azure_rm_subnet:
      resource_group: the1bit-rg-custom
      name: the1bit-subnet-be
      address_prefix: "79.0.1.0/24"
      virtual_network: the1bit-vnet
  - name: Create public IP address
    azure_rm_publicipaddress:
      resource_group: the1bit-rg-custom
      allocation_method: Dynamic
      name: "{{vm_name}}-pip"
  - name: Create Network Security Group - FE -  that allows SSH
    azure_rm_securitygroup:
      resource_group: the1bit-rg-custom
      name: the1bit-nsg-fe
      rules:
        - name: SSH
          protocol: Tcp
          destination_port_range: 22
          access: Allow
          priority: 1001
          direction: Inbound
  - name: Create Network Security Group - BE
    azure_rm_securitygroup:
      resource_group: the1bit-rg-custom
      name: the1bit-nsg-be
  - name: Create virtual network inteface card - FE
    azure_rm_networkinterface:
      resource_group: the1bit-rg-custom
      name: "{{vm_name}}-nic-fe"
      virtual_network: the1bit-vnet
      subnet: the1bit-subnet-fe
      security_group: the1bit-nsg-fe
      ip_configurations:
        - name: ipconfig1
          private_ip_allocation_method: Static
          private_ip_address: "79.0.0.12"
          public_ip_address_name: "{{vm_name}}-pip"
          primary: true
  - name: Create virtual network inteface card - BE
    azure_rm_networkinterface:
      resource_group: the1bit-rg-custom
      name: "{{vm_name}}-nic-be"
      virtual_network: the1bit-vnet
      subnet: the1bit-subnet-be
      security_group: the1bit-nsg-be
      ip_configurations:
        - name: ipconfig1
          private_ip_allocation_method: Static
          private_ip_address: "79.0.1.12"
  - name: Create an availability set with UD - 5, FD - 3
    azure_rm_availabilityset:
      name: the1bit-availabilityset-custom
      resource_group: the1bit-rg-custom
      platform_update_domain_count: 5
      platform_fault_domain_count: 3
      sku: Aligned
  - name: Create VM - 2 NICs
    azure_rm_virtualmachine:
      resource_group: the1bit-rg-custom
      name: "{{vm_name}}"
      vm_size: Standard_DS12_v2
      availability_set: the1bit-availabilityset-custom
      managed_disk_type: Standard_LRS
      admin_username: localadmin
      ssh_password_enabled: false
      ssh_public_keys:
        - path: /home/localadmin/.ssh/authorized_keys
          key_data: "ssh-rsa AAAAB3NzaC1yc2EAAAABJQAAAQEAw7MZOoRarCnS3Tg9G6HBd4bdUmEldXKRwAb7WZ4aW7oHOEZZCiQPFVBjM0G15Kz+UN5fokewxO9Ck902pAKLNlJmQLnZUol3M3U0zoEtY/dS6U7KuppqS9QsvgNgqjJuTQet+WnMfQbfGP6aqQ/Dk+9uEYnRJPrW1aiZVCBsT09hD2CtewHwKvVm/gHNT7aoIKzbRCwXznHMe7Qr30sye19P80Ha67O9Z66Jwgdytp4V88KcyzreJGgTyzf77kkIfHU0wveSv+NboEmrMzVpsaLeNgCeBquTrOHmR0f1aIynaR4ni/IdO2kuGMDPtnOvJwGu5nXdYEkNmzQRaPlv0Q=="
      network_interface_names:
      - "{{vm_name}}-nic-fe"
      - "{{vm_name}}-nic-be"
      image:
        offer: CentOS
        publisher: OpenLogic
        sku: '7.3'
        version: latest
      data_disks:
        - lun: 0
          disk_size_gb: 128
          managed_disk_type: Premium_LRS
