- name: Health checks for computers
  hosts: vms
  gather_facts: no
  tasks:
  - name: Execute local script for health checking
    script: "{{ mainpath }}/files/healthcheck.sh"
    register: script_result
    failed_when: "'ERROR' in script_result.stdout"
    changed_when: "'CHANGED' in script_result.stdout"
